{{- if and .Values.components.cloudnativepg.enabled .Values.cloudnativepgCluster.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cloudnativepgCluster.name | quote }}
  labels:
    app.kubernetes.io/name: pulse-platform
    app.kubernetes.io/part-of: ecoflow-pulse
spec:
  {{- if and .Values.components.timescaledb.enabled .Values.cloudnativepgCluster.timescaledb.enabled }}
  postgresUID: {{ .Values.cloudnativepgCluster.timescaledb.postgresUID }}
  postgresGID: {{ .Values.cloudnativepgCluster.timescaledb.postgresGID }}
  {{- else }}
  postgresUID: {{ .Values.cloudnativepgCluster.postgresUID }}
  postgresGID: {{ .Values.cloudnativepgCluster.postgresGID }}
  {{- end }}
  {{- if and .Values.components.timescaledb.enabled .Values.cloudnativepgCluster.timescaledb.enabled }}
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: {{ .Values.cloudnativepgCluster.timescaledb.imageCatalog.name | quote }}
    major: {{ .Values.cloudnativepgCluster.timescaledb.imageCatalog.major }}
  {{- end }}
  instances: {{ .Values.cloudnativepgCluster.instances }}
  bootstrap:
    initdb:
      database: {{ .Values.cloudnativepgCluster.bootstrap.database | quote }}
      owner: {{ .Values.cloudnativepgCluster.bootstrap.owner | quote }}
      secret:
        name: {{ .Values.cloudnativepgCluster.bootstrap.appSecretName | quote }}
      {{- if and .Values.components.timescaledb.enabled .Values.cloudnativepgCluster.timescaledb.enabled }}
      postInitApplicationSQL:
        {{- range .Values.cloudnativepgCluster.timescaledb.postInitApplicationSQL }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
  {{- if and .Values.components.timescaledb.enabled .Values.cloudnativepgCluster.timescaledb.enabled }}
  postgresql:
    shared_preload_libraries:
      - timescaledb
  {{- end }}
  resources:
    requests:
      cpu: {{ .Values.cloudnativepgCluster.resources.requests.cpu | quote }}
      memory: {{ .Values.cloudnativepgCluster.resources.requests.memory | quote }}
    limits:
      cpu: {{ .Values.cloudnativepgCluster.resources.limits.cpu | quote }}
      memory: {{ .Values.cloudnativepgCluster.resources.limits.memory | quote }}
  storage:
    {{- with .Values.cloudnativepgCluster.storage.storageClass }}
    storageClass: {{ . | quote }}
    {{- end }}
    size: {{ .Values.cloudnativepgCluster.storage.size | quote }}
{{- end }}
