{{- if and .Values.components.cloudnativepg.enabled .Values.cloudnativepgCluster.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudnativepgCluster.bootstrap.appSecretName | quote }}
  labels:
    app.kubernetes.io/name: pulse-platform
    app.kubernetes.io/part-of: ecoflow-pulse
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.cloudnativepgCluster.bootstrap.appUser | quote }}
  password: {{ .Values.cloudnativepgCluster.bootstrap.appPassword | quote }}
{{- end }}
