{{- if and .Values.components.cloudnativepg.enabled .Values.cloudnativepgCluster.enabled .Values.cloudnativepgContract.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudnativepgContract.connectionSecretName | quote }}
  labels:
    app.kubernetes.io/name: pulse-platform
    app.kubernetes.io/part-of: ecoflow-pulse
type: Opaque
stringData:
  host: {{ .Values.cloudnativepgContract.service.rw | quote }}
  port: {{ .Values.cloudnativepgContract.port | quote }}
  database: {{ .Values.cloudnativepgContract.database | quote }}
  username: {{ .Values.cloudnativepgCluster.bootstrap.appUser | quote }}
  password: {{ .Values.cloudnativepgCluster.bootstrap.appPassword | quote }}
  url: {{ printf "postgresql://%s:%s@%s:%v/%s" .Values.cloudnativepgCluster.bootstrap.appUser .Values.cloudnativepgCluster.bootstrap.appPassword .Values.cloudnativepgContract.service.rw .Values.cloudnativepgContract.port .Values.cloudnativepgContract.database | quote }}
{{- end }}
