{{- if and .Values.components.cloudnativepg.enabled .Values.components.timescaledb.enabled .Values.cloudnativepgCluster.enabled .Values.cloudnativepgCluster.timescaledb.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: {{ .Values.cloudnativepgCluster.timescaledb.imageCatalog.name | quote }}
  labels:
    app.kubernetes.io/name: pulse-platform
    app.kubernetes.io/part-of: ecoflow-pulse
spec:
  images:
    - major: {{ .Values.cloudnativepgCluster.timescaledb.imageCatalog.major }}
      image: {{ .Values.cloudnativepgCluster.timescaledb.imageCatalog.image | quote }}
{{- end }}
