{{- if and .Values.components.keycloak.enabled .Values.keycloakRealm.enabled (not .Values.secretManager.keycloakSocialExternalSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloakRealm.socialSecretName | quote }}
  labels:
    app.kubernetes.io/name: pulse-platform
    app.kubernetes.io/part-of: ecoflow-pulse
type: Opaque
stringData:
  KEYCLOAK_SOCIAL_GOOGLE_CLIENT_ID: {{ .Values.keycloakRealm.google.clientId | quote }}
  KEYCLOAK_SOCIAL_GOOGLE_CLIENT_SECRET: {{ .Values.keycloakRealm.google.clientSecret | quote }}
  KEYCLOAK_SOCIAL_FACEBOOK_CLIENT_ID: {{ .Values.keycloakRealm.facebook.clientId | quote }}
  KEYCLOAK_SOCIAL_FACEBOOK_CLIENT_SECRET: {{ .Values.keycloakRealm.facebook.clientSecret | quote }}
{{- end }}
