{{- if .Values.scaffold.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pulse-platform-scaffold
  labels:
    app.kubernetes.io/name: pulse-platform
    app.kubernetes.io/part-of: ecoflow-pulse
data:
  environment: {{ .Values.global.environment | quote }}
  message: {{ .Values.scaffold.message | quote }}
{{- end }}
