{{- if and .Values.secretManager.enabled .Values.secretManager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pulse-platform.secretManagerServiceAccountName" . }}
  labels:
    {{- include "pulse-platform.labels" . | nindent 4 }}
  {{- with .Values.secretManager.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.secretManager.serviceAccount.automountServiceAccountToken }}
---
{{- end }}
{{- if and .Values.secretManager.enabled .Values.secretManager.secretStore.create }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretManager.secretStore.name }}
  labels:
    {{- include "pulse-platform.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.secretManager.secretStore.projectId | quote }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.secretManager.secretStore.clusterLocation | quote }}
          clusterName: {{ .Values.secretManager.secretStore.clusterName | quote }}
          serviceAccountRef:
            name: {{ include "pulse-platform.secretManagerServiceAccountName" . | quote }}
---
{{- end }}
{{- if and .Values.secretManager.enabled .Values.secretManager.keycloakSocialExternalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.keycloakRealm.socialSecretName | quote }}
  labels:
    {{- include "pulse-platform.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secretManager.keycloakSocialExternalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.secretManager.secretStore.kind | quote }}
    name: {{ .Values.secretManager.secretStore.name | quote }}
  target:
    name: {{ default .Values.keycloakRealm.socialSecretName .Values.secretManager.keycloakSocialExternalSecret.targetSecretName | quote }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    {{- with .Values.secretManager.keycloakSocialExternalSecret.data.googleClientId }}
    - secretKey: KEYCLOAK_SOCIAL_GOOGLE_CLIENT_ID
      remoteRef:
        key: {{ . | quote }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    {{- end }}
    {{- with .Values.secretManager.keycloakSocialExternalSecret.data.googleClientSecret }}
    - secretKey: KEYCLOAK_SOCIAL_GOOGLE_CLIENT_SECRET
      remoteRef:
        key: {{ . | quote }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    {{- end }}
    {{- with .Values.secretManager.keycloakSocialExternalSecret.data.facebookClientId }}
    - secretKey: KEYCLOAK_SOCIAL_FACEBOOK_CLIENT_ID
      remoteRef:
        key: {{ . | quote }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    {{- end }}
    {{- with .Values.secretManager.keycloakSocialExternalSecret.data.facebookClientSecret }}
    - secretKey: KEYCLOAK_SOCIAL_FACEBOOK_CLIENT_SECRET
      remoteRef:
        key: {{ . | quote }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    {{- end }}
{{- end }}
