#!/usr/bin/env bash
set -euo pipefail

output_file=""

usage() {
  cat <<'USAGE'
Usage: pulse-appliance-render-release-values.sh --output FILE

Renders install-local Pi appliance release values from published image digests.

Required environment:
  PULSE_PI_IMAGE_NAMESPACE
  PULSE_PI_PUBLIC_APP_IMAGE_DIGEST
  PULSE_PI_REALTIME_GATEWAY_IMAGE_DIGEST
  PULSE_PI_SERVICES_IMAGE_DIGEST

Optional environment:
  PULSE_PI_IMAGE_REGISTRY                 default: ghcr.io
  PULSE_PI_PUBLIC_APP_IMAGE_REPOSITORY    default: $registry/$namespace/pulse-platform
  PULSE_PI_REALTIME_GATEWAY_IMAGE_REPOSITORY
                                           default: $registry/$namespace/pulse-realtime-gateway
  PULSE_PI_SERVICES_IMAGE_REPOSITORY      default: $registry/$namespace/services
  PULSE_PI_IMAGE_PULL_SECRET              optional pull secret name rendered into both charts
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --output)
      output_file="${2:?--output requires a file path}"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

if [ -z "$output_file" ]; then
  echo "--output is required" >&2
  usage >&2
  exit 2
fi

require_env() {
  local name="$1"
  if [ -z "${!name:-}" ]; then
    echo "$name is required" >&2
    exit 1
  fi
}

validate_digest() {
  local name="$1"
  local value="${!name}"
  if [[ ! "$value" =~ ^sha256:[0-9a-f]{64}$ ]]; then
    echo "$name must be a sha256:<64 lowercase hex chars> digest" >&2
    exit 1
  fi
}

require_env PULSE_PI_IMAGE_NAMESPACE
require_env PULSE_PI_PUBLIC_APP_IMAGE_DIGEST
require_env PULSE_PI_REALTIME_GATEWAY_IMAGE_DIGEST
require_env PULSE_PI_SERVICES_IMAGE_DIGEST

validate_digest PULSE_PI_PUBLIC_APP_IMAGE_DIGEST
validate_digest PULSE_PI_REALTIME_GATEWAY_IMAGE_DIGEST
validate_digest PULSE_PI_SERVICES_IMAGE_DIGEST

registry="${PULSE_PI_IMAGE_REGISTRY:-ghcr.io}"
namespace="$PULSE_PI_IMAGE_NAMESPACE"
public_app_repo="${PULSE_PI_PUBLIC_APP_IMAGE_REPOSITORY:-$registry/$namespace/pulse-platform}"
realtime_gateway_repo="${PULSE_PI_REALTIME_GATEWAY_IMAGE_REPOSITORY:-$registry/$namespace/pulse-realtime-gateway}"
services_repo="${PULSE_PI_SERVICES_IMAGE_REPOSITORY:-$registry/$namespace/services}"
image_pull_secret="${PULSE_PI_IMAGE_PULL_SECRET:-}"

if [ -n "$image_pull_secret" ] && [[ ! "$image_pull_secret" =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$ ]]; then
  echo "PULSE_PI_IMAGE_PULL_SECRET must be a Kubernetes DNS label" >&2
  exit 1
fi

umask 077
mkdir -p "$(dirname "$output_file")"

{
  cat <<YAML
# Generated by deploy/appliance/pi5/pulse-appliance-render-release-values.sh.
# Keep this file install-local; do not commit filled release values.

runtime:
YAML

  if [ -n "$image_pull_secret" ]; then
    cat <<YAML
  imagePullSecrets:
    - name: ${image_pull_secret}
YAML
  else
    cat <<'YAML'
  imagePullSecrets: []
YAML
  fi

  cat <<YAML
  publicApp:
    image:
      repository: ${public_app_repo}
      tag: ""
      digest: ${PULSE_PI_PUBLIC_APP_IMAGE_DIGEST}
      pullPolicy: IfNotPresent
  realtimeGateway:
    image:
      repository: ${realtime_gateway_repo}
      tag: ""
      digest: ${PULSE_PI_REALTIME_GATEWAY_IMAGE_DIGEST}
      pullPolicy: IfNotPresent
  image:
    repository: ${services_repo}
    tag: ""
    digest: ${PULSE_PI_SERVICES_IMAGE_DIGEST}
    pullPolicy: IfNotPresent
  gcsCredentials:
    enabled: true
    secretName: pulse-services-gcs-credentials
    secretKey: key.json
    fileName: key.json
    mountPath: /var/run/pulse-gcs
YAML
} >"$output_file"
