apiVersion: v1
kind: ResourceQuota
metadata:
  name: pulse-dev-quota
  namespace: pulse-dev
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "60"
    persistentvolumeclaims: "20"
