apiVersion: v1
kind: LimitRange
metadata:
  name: pulse-dev-limits
  namespace: pulse-dev
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 256Mi
      default:
        cpu: 500m
        memory: 512Mi
