components:
  keycloak:
    enabled: false
  ingressNginx:
    enabled: false
  certManager:
    enabled: false

runtime:
  publicApp:
    enabled: false
  realtimeGateway:
    enabled: false

keycloakRealm:
  enabled: false

nats:
  natsBox:
    enabled: false

cloudnative-pg:
  nodeSelector: null
  tolerations:
    - key: workload
      operator: Equal
      value: stateful
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                  - stateful-pool-medium
                  - stateful-pool-ha-medium
                  - stateful-pool-quorum-medium

external-secrets:
  nodeSelector: null
  tolerations:
    - key: workload
      operator: Equal
      value: stateful
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                  - stateful-pool-medium
                  - stateful-pool-ha-medium
                  - stateful-pool-quorum-medium
  webhook:
    nodeSelector: null
    tolerations:
      - key: workload
        operator: Equal
        value: stateful
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                    - stateful-pool-medium
                    - stateful-pool-ha-medium
                    - stateful-pool-quorum-medium
  certController:
    nodeSelector: null
    tolerations:
      - key: workload
        operator: Equal
        value: stateful
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                    - stateful-pool-medium
                    - stateful-pool-ha-medium
                    - stateful-pool-quorum-medium
