{{- if and .Values.runtime.secretManager.enabled .Values.runtime.secretManager.secretStore.create }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.runtime.secretManager.secretStore.name }}
  labels:
    {{- include "pulse-services.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.runtime.secretManager.secretStore.projectId | quote }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.runtime.secretManager.secretStore.clusterLocation | quote }}
          clusterName: {{ .Values.runtime.secretManager.secretStore.clusterName | quote }}
          serviceAccountRef:
            name: {{ include "pulse-services.serviceAccountName" . | quote }}
---
{{- end }}
{{- if and .Values.runtime.secretManager.enabled .Values.runtime.secretManager.runtimeExternalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "pulse-services.runtimeSecretName" . }}
  labels:
    {{- include "pulse-services.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.runtime.secretManager.runtimeExternalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.runtime.secretManager.secretStore.kind | quote }}
    name: {{ .Values.runtime.secretManager.secretStore.name | quote }}
  target:
    name: {{ default (include "pulse-services.runtimeSecretName" .) .Values.runtime.secretManager.runtimeExternalSecret.targetSecretName | quote }}
    creationPolicy: Owner
  data:
    {{- with .Values.runtime.secretManager.runtimeExternalSecret.data.controlPlaneDBDSN }}
    - secretKey: CONTROL_PLANE_DB_DSN
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.runtime.secretManager.runtimeExternalSecret.data.archiveManifestDBDSN }}
    - secretKey: ARCHIVE_MANIFEST_DB_DSN
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.runtime.secretManager.runtimeExternalSecret.data.archiveObjectAccessKey }}
    - secretKey: ARCHIVE_OBJECT_ACCESS_KEY
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.runtime.secretManager.runtimeExternalSecret.data.archiveObjectSecretKey }}
    - secretKey: ARCHIVE_OBJECT_SECRET_KEY
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.runtime.secretManager.runtimeExternalSecret.data.pulseMqttEmulatorAccessKey }}
    - secretKey: PULSE_MQTT_EMULATOR_ACCESS_KEY
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.runtime.secretManager.runtimeExternalSecret.data.pulseMqttEmulatorSecretKey }}
    - secretKey: PULSE_MQTT_EMULATOR_SECRET_KEY
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.runtime.secretManager.runtimeExternalSecret.data.pulseMqttEmulatorMQTTUsername }}
    - secretKey: PULSE_MQTT_EMULATOR_MQTT_USERNAME
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.runtime.secretManager.runtimeExternalSecret.data.pulseMqttEmulatorMQTTPassword }}
    - secretKey: PULSE_MQTT_EMULATOR_MQTT_PASSWORD
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
{{- end }}
