global:
  environment: dev

scaffold:
  enabled: true
  message: "pulse-services dev scaffold"

runtime:
  env:
    dbSchemaSearchPath: ""
  migrations:
    enabled: false
    namespace: pulse-platform
    db:
      host: pulse-platform-core-rw
      port: 5432
      name: pulse
      sslmode: disable
      credentialsSecretName: pulse-platform-core-app
      usernameKey: username
      passwordKey: password
    policy:
      rolloutEnv: dev
      requireBackup: false
      backupRef: ""
      forwardOnly: true
  workers:
    grpcApi:
      enabled: true
      replicaCount: 2
