apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulse-services
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: ecoflow-pulse
spec:
  project: default
  source:
    repoURL: https://github.com/jpaljasma/ecoflow-pulse.git
    targetRevision: main
    path: deploy/charts/pulse-services
    helm:
      valueFiles:
        - ../../env/dev/values.services.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pulse-services
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
