apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulse-platform
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: ecoflow-pulse
spec:
  project: default
  source:
    repoURL: https://github.com/jpaljasma/ecoflow-pulse.git
    targetRevision: main
    path: deploy/charts/pulse-platform
    helm:
      valueFiles:
        - ../../env/dev/values.platform.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pulse-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
